AWSTemplateFormatVersion: "2010-09-09"

Description: Zuora invoice management such as refunds, downloading PDF invoices

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - DEV
      - CODE
      - PROD
    Default: CODE

Conditions:
  IsProd: !Equals [!Ref "Stage", "PROD"]

Resources:

  # ****************************************************************************
  # Alarms
  # ****************************************************************************
  FailedRefundAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      AlarmName: "URGENT 9-5 - PROD: Failed to apply refund to Zuora invoice"
      AlarmDescription: Urgently perform manual cleanup as documented at https://github.com/guardian/invoicing-api
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:MarioTest
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref RefundLambda
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
    DependsOn:
      - InvoicingLambdaRole

  FailedInvoicesAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      AlarmName: "URGENT 9-5 - PROD: Failed to fetch Zuora invoice by account"
      AlarmDescription: |
        - manage-frontend user will not be able to see/download invoices
        - https://github.com/guardian/invoicing-api/blob/master/src/main/scala/com/gu/invoicing/invoice/README.md
        - export AWS_DEFAULT_REGION=eu-west-1 && awslogs get --profile membership /aws/lambda/invoicing-api-invoices-PROD --start='DD/mm/yyyy HH:MM' --end='DD/mm/yyyy HH:MM'
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:MarioTest
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref InvoicesLambda
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
    DependsOn:
      - InvoicingLambdaRole

  # ****************************************************************************
  # Lambdas
  # ****************************************************************************

  RefundLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Apply refund to Zuora invoice by adjusting invoice items
      FunctionName: !Sub invoicing-api-refund-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub support/${Stage}/invoicing-api/invoicing-api.jar
      Handler: com.gu.invoicing.refund.Lambda::handleRequest
      Environment:
        Variables:
          Stage: !Ref Stage
          Config: !Sub '{{resolve:ssm:/invoicing-api/${Stage}/config:1}}'
      Role: !GetAtt InvoicingLambdaRole.Arn
      MemorySize: 3008
      Runtime: java8
      Timeout: 900
    DependsOn:
      - InvoicingLambdaRole

  InvoicesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Retrieve all invoices with payment methods by accountId
      FunctionName: !Sub invoicing-api-invoices-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub support/${Stage}/invoicing-api/invoicing-api.jar
      Handler: com.gu.invoicing.invoice.Lambda::handleRequest
      Environment:
        Variables:
          Stage: !Ref Stage
          Config: !Sub '{{resolve:ssm:/invoicing-api/${Stage}/config:1}}'
      Role: !GetAtt InvoicingLambdaRole.Arn
      MemorySize: 3008
      Runtime: java8
      Timeout: 900
    DependsOn:
      - InvoicingLambdaRole

  # ****************************************************************************
  # API
  # ****************************************************************************
  InvoicingApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub invoicing-api-${Stage}
      Description: Zuora invoice management (refunds)

  InvoicingApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref InvoicingApi
      DeploymentId: !Ref InvoicingApiDeployment
      StageName: !Sub ${Stage}
    DependsOn:
      - RefundMethod

  InvoicingApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref InvoicingApi
    DependsOn:
      - RefundMethod

  InvoicingApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: invoicing-api
      ApiStages:
        - ApiId: !Ref InvoicingApi
          Stage: !Ref Stage
    DependsOn:
      - InvoicingApi
      - InvoicingApiStage

  InvoicingApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Description: Used by https://github.com/guardian/invoicing-api
      Enabled: true
      Name: !Sub invoicing-api-key-${Stage}
      StageKeys:
        - RestApiId: !Ref InvoicingApi
          StageName: !Sub ${Stage}
    DependsOn:
      - InvoicingApi
      - InvoicingApiStage

  InvoicingApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref InvoicingApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref InvoicingApiUsagePlan
    DependsOn:
      - InvoicingApiKey
      - InvoicingApiUsagePlan


  # ****************************************************************************
  # POST /refund
  # ****************************************************************************
  RefundEndpoint:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref InvoicingApi
      ParentId: !GetAtt InvoicingApi.RootResourceId
      PathPart: refund
    DependsOn: InvoicingApi

  RefundMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: true
      AuthorizationType: NONE
      RestApiId: !Ref InvoicingApi
      ResourceId: !Ref RefundEndpoint
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST # this for the interaction between API Gateway and Lambda and MUST be POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RefundLambda.Arn}/invocations
    DependsOn:
      - InvoicingApi
      - RefundEndpoint
      - RefundLambda

  # ****************************************************************************
  # GET /invoices/{accountId}
  # ****************************************************************************
  InvoicesEndpoint:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref InvoicingApi
      ParentId: !GetAtt InvoicingApi.RootResourceId
      PathPart: invoices
    DependsOn: InvoicingApi

  InvoicesAccountIdPath:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref InvoicingApi
      ParentId: !Ref InvoicesEndpoint
      PathPart: "{accountId}"
    DependsOn:
      - InvoicingApi
      - InvoicesEndpoint

  InvoicesEndpointGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: AWS_IAM
      ApiKeyRequired: true
      RestApiId: !Ref InvoicingApi
      ResourceId: !Ref InvoicesAccountIdPath
      HttpMethod: GET
      RequestParameters:
        method.request.path.accountId: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST # this for the interaction between API Gateway and Lambda and MUST be POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InvoicesLambda.Arn}/invocations
    DependsOn:
      - InvoicingApi
      - InvoicesLambda
      - InvoicesAccountIdPath

  # ****************************************************************************
  # Access control
  # ****************************************************************************

  RefundLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Sub invoicing-api-refund-${Stage}
      Principal: apigateway.amazonaws.com
    DependsOn:
      - RefundLambda
      - RefundMethod

  InvoicesLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Sub invoicing-api-invoices-${Stage}
      Principal: apigateway.amazonaws.com
    DependsOn:
      - InvoicesLambda

  InvoicingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/invoicing-api-refund-${Stage}:log-stream:*
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/invoicing-api-invoices-${Stage}:log-stream:*

        - PolicyName: ReadPrivateCredentials
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub arn:aws:s3:::gu-reader-revenue-private/membership/support-service-lambdas/${Stage}/zuoraRest-${Stage}*.json
